# Generated by Django 2.1.5 on 2019-01-29 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='common.BaseModel')),
                ('year', models.IntegerField()),
                ('color', models.CharField(max_length=20)),
                ('mileage', models.IntegerField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=128, null=True)),
                ('price', models.FloatField()),
                ('contact', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.City')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.Variant')),
            ],
            bases=('common.basemodel',),
        ),
    ]
