# Generated by Django 2.1.5 on 2019-03-01 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_auto_20190207_0246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoritedad',
            name='ad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_ads', to='listings.Ad'),
        ),
    ]
