# Generated by Django 2.1.5 on 2019-01-30 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
        ('listings', '0003_ad_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AdFeatures',
            new_name='AdFeature',
        ),
    ]
