# Generated by Django 2.1.5 on 2019-03-14 06:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_auto_20190301_1514'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ad',
            old_name='description',
            new_name='comments',
        ),
        migrations.AlterField(
            model_name='ad',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
