# Generated by Django 2.1.5 on 2019-01-30 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
        ('listings', '0004_auto_20190130_2351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adfeature',
            name='ad',
        ),
        migrations.RemoveField(
            model_name='adfeature',
            name='feature',
        ),
        migrations.AddField(
            model_name='ad',
            name='features',
            field=models.ManyToManyField(related_name='ads', to='vehicles.Feature'),
        ),
        migrations.DeleteModel(
            name='AdFeature',
        ),
    ]
