# Generated by Django 2.1.5 on 2019-03-21 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_adphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='youtube_link',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
