# Generated by Django 2.1.5 on 2019-02-01 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0003_auto_20190201_0032'),
        ('listings', '0006_ad_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vehicles.Model'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vehicles.Variant'),
        ),
    ]
