# Generated by Django 2.1.5 on 2019-03-26 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_ad_youtube_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='body_type',
            field=models.IntegerField(choices=[(1, 'Sedan'), (2, 'Cabriolet'), (3, 'Wagon')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ad',
            name='feul_type',
            field=models.IntegerField(choices=[(1, 'Petrol'), (2, 'Diesel')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ad',
            name='modification_type',
            field=models.IntegerField(choices=[(1, '1.8L'), (2, '2.0L'), (3, '2.5L'), (4, '3.5L'), (5, '5.5L')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ad',
            name='right_handed_drive',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ad',
            name='transmission_type',
            field=models.IntegerField(choices=[(1, 'Manual'), (2, 'Cabriolet'), (3, 'Wagon')], default=1),
            preserve_default=False,
        ),
    ]
