# Generated by Django 2.1.5 on 2019-03-26 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_auto_20190326_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='gas_equipment',
            field=models.BooleanField(default=False),
        ),
    ]
