# Generated by Django 2.1.5 on 2019-03-26 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0008_ad_gas_equipment'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='assembly_type',
            field=models.IntegerField(choices=[(1, 'Pakistan'), (2, 'Imported')], default=1),
            preserve_default=False,
        ),
    ]
