# Generated by Django 2.1.5 on 2019-03-26 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0009_ad_assembly_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ad',
            old_name='feul_type',
            new_name='fuel_type',
        ),
    ]
