# Generated by Django 2.1.5 on 2019-04-01 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0011_auto_20190329_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='contact_person',
            field=models.CharField(default='Imran Ali', max_length=128),
        ),
    ]
