# Generated by Django 2.1.5 on 2019-04-01 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_auto_20190207_0246'),
        ('listings', '0012_ad_contact_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='registration_city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='common.City'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ad',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registered_vehicles', to='common.City'),
        ),
    ]
