# Generated by Django 2.1.5 on 2019-04-01 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0013_auto_20190401_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ads', to='common.City'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='registration_city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registered_vehicle_ads', to='common.City'),
        ),
    ]
