# Generated by Django 2.1.5 on 2019-04-01 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0014_auto_20190401_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='contact_person',
            field=models.CharField(max_length=128),
        ),
    ]
