# Generated by Django 2.1.5 on 2019-05-10 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0016_auto_20190508_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyadviews',
            name='ad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_views', to='listings.Ad'),
        ),
    ]
