# Generated by Django 2.1.5 on 2019-03-08 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20190301_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_type',
            field=models.IntegerField(choices=[(1, 'Admin'), (2, 'Agent'), (3, 'Regular'), (4, 'Showroom')], default=3),
        ),
    ]
