# Generated by Django 2.1.5 on 2019-04-26 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20190419_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temporaryuser',
            name='contact',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
