# Generated by Django 2.1.5 on 2019-02-06 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=128, unique=True)),
                ('amount', models.FloatField()),
                ('package', models.IntegerField(choices=[(1, 'Featured'), (2, 'Autosale')])),
                ('ad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='listings.Ad')),
            ],
        ),
    ]
