# Generated by Django 2.1.5 on 2019-03-08 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_auto_20190207_0246'),
    ]

    operations = [
        migrations.AddField(
            model_name='make',
            name='is_popular',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
