# Generated by Django 2.1.5 on 2019-01-31 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_make_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='vehicle_type',
            field=models.IntegerField(choices=[(1, 'Car'), (2, 'Bike')]),
        ),
        migrations.AlterField(
            model_name='make',
            name='vehicle_type',
            field=models.IntegerField(choices=[(1, 'Car'), (2, 'Bike')]),
        ),
    ]
