# Generated by Django 2.1.5 on 2019-03-08 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0003_make_is_popular'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='is_popular',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
