# Generated by Django 2.1.5 on 2019-03-29 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0004_model_is_popular'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
