# Generated by Django 2.1.5 on 2019-04-04 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0005_feature_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='code',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
